# Generated by Django 2.2.8 on 2020-01-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
    ]
