# Generated by Django 2.2.8 on 2020-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bank_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
