# Generated by Django 2.2.8 on 2020-01-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200106_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
